// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Order struct {
	ID                int32         `json:"id"`
	UserID            sql.NullInt32 `json:"user_id"`
	CustomerName      string        `json:"customer_name"`
	CustomerPhone     string        `json:"customer_phone"`
	DeliveryAddress   string        `json:"delivery_address"`
	OrderTotal        int32         `json:"order_total"`
	PaymentStatus     string        `json:"payment_status"`
	FulfillmentStatus string        `json:"fulfillment_status"`
	CreatedAt         time.Time     `json:"created_at"`
	UpdatedAt         time.Time     `json:"updated_at"`
}

type OrderItem struct {
	ID               int32  `json:"id"`
	OrderID          int32  `json:"order_id"`
	MenuID           int32  `json:"menu_id"`
	MenuNameSnapshot string `json:"menu_name_snapshot"`
	UnitPrice        int32  `json:"unit_price"`
	Quantity         int32  `json:"quantity"`
	ModifiersTotal   int32  `json:"modifiers_total"`
	ItemTotal        int32  `json:"item_total"`
}

type OrderItemModifier struct {
	ID                        int32  `json:"id"`
	OrderItemID               int32  `json:"order_item_id"`
	ModifierGroupNameSnapshot string `json:"modifier_group_name_snapshot"`
	ModifierItemNameSnapshot  string `json:"modifier_item_name_snapshot"`
	ModifierPrice             int32  `json:"modifier_price"`
	Quantity                  int32  `json:"quantity"`
}

type Payment struct {
	ID                   int32          `json:"id"`
	OrderID              int32          `json:"order_id"`
	ExternalID           string         `json:"external_id"`
	GatewayTransactionID string         `json:"gateway_transaction_id"`
	GatewayName          string         `json:"gateway_name"`
	Amount               int32          `json:"amount"`
	PaymentMethod        sql.NullString `json:"payment_method"`
	PaymentChannel       sql.NullString `json:"payment_channel"`
	Status               string         `json:"status"`
	CheckoutUrl          sql.NullString `json:"checkout_url"`
	CallbackToken        sql.NullString `json:"callback_token"`
	PaidAt               sql.NullTime   `json:"paid_at"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}
