// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"
	"database/sql"
)

const cancelOrder = `-- name: CancelOrder :exec
UPDATE orders
SET fulfillment_status = 'canceled',
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND payment_status = 'pending'
  AND fulfillment_status = 'new'
`

func (q *Queries) CancelOrder(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, cancelOrder, id)
	return err
}

const completeOrder = `-- name: CompleteOrder :exec
UPDATE orders
SET fulfillment_status = 'completed',
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND payment_status = 'paid'
  AND fulfillment_status = 'delivering'
`

func (q *Queries) CompleteOrder(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, completeOrder, id)
	return err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    user_id,
    customer_name,
    customer_phone,
    delivery_address,
    order_total,
    payment_status,
    fulfillment_status
  )
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
  )
RETURNING id, user_id, customer_name, customer_phone, delivery_address, order_total, payment_status, fulfillment_status, created_at, updated_at
`

type CreateOrderParams struct {
	UserID            sql.NullInt32 `json:"user_id"`
	CustomerName      string        `json:"customer_name"`
	CustomerPhone     string        `json:"customer_phone"`
	DeliveryAddress   string        `json:"delivery_address"`
	OrderTotal        int32         `json:"order_total"`
	PaymentStatus     string        `json:"payment_status"`
	FulfillmentStatus string        `json:"fulfillment_status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.UserID,
		arg.CustomerName,
		arg.CustomerPhone,
		arg.DeliveryAddress,
		arg.OrderTotal,
		arg.PaymentStatus,
		arg.FulfillmentStatus,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.DeliveryAddress,
		&i.OrderTotal,
		&i.PaymentStatus,
		&i.FulfillmentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllOrders = `-- name: GetAllOrders :many
SELECT id, user_id, customer_name, customer_phone, delivery_address, order_total, payment_status, fulfillment_status, created_at, updated_at
FROM orders
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type GetAllOrdersParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) GetAllOrders(ctx context.Context, arg GetAllOrdersParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getAllOrders, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.DeliveryAddress,
			&i.OrderTotal,
			&i.PaymentStatus,
			&i.FulfillmentStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderById = `-- name: GetOrderById :one
SELECT id, user_id, customer_name, customer_phone, delivery_address, order_total, payment_status, fulfillment_status, created_at, updated_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderById(ctx context.Context, id int32) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderById, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.DeliveryAddress,
		&i.OrderTotal,
		&i.PaymentStatus,
		&i.FulfillmentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrdersByUserId = `-- name: GetOrdersByUserId :many
SELECT id, user_id, customer_name, customer_phone, delivery_address, order_total, payment_status, fulfillment_status, created_at, updated_at
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetOrdersByUserId(ctx context.Context, userID sql.NullInt32) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.DeliveryAddress,
			&i.OrderTotal,
			&i.PaymentStatus,
			&i.FulfillmentStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderDelivering = `-- name: MarkOrderDelivering :exec
UPDATE orders
SET fulfillment_status = 'delivering',
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND payment_status = 'paid'
  AND fulfillment_status = 'preparing'
`

func (q *Queries) MarkOrderDelivering(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, markOrderDelivering, id)
	return err
}

const markOrderPaid = `-- name: MarkOrderPaid :exec
UPDATE orders
SET payment_status = 'paid',
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND payment_status = 'pending'
`

func (q *Queries) MarkOrderPaid(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, markOrderPaid, id)
	return err
}

const markOrderPaymentExpired = `-- name: MarkOrderPaymentExpired :exec
UPDATE orders
SET payment_status = 'expired',
  fulfillment_status = 'canceled',
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND payment_status = 'pending'
  AND fulfillment_status = 'new'
`

func (q *Queries) MarkOrderPaymentExpired(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, markOrderPaymentExpired, id)
	return err
}

const markOrderPaymentFailed = `-- name: MarkOrderPaymentFailed :exec
UPDATE orders
SET payment_status = 'failed',
  fulfillment_status = 'canceled',
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND payment_status = 'pending'
  AND fulfillment_status = 'new'
`

func (q *Queries) MarkOrderPaymentFailed(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, markOrderPaymentFailed, id)
	return err
}

const startPreparingOrder = `-- name: StartPreparingOrder :exec
UPDATE orders
SET fulfillment_status = 'preparing',
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND payment_status = 'paid'
  AND fulfillment_status = 'new'
`

func (q *Queries) StartPreparingOrder(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, startPreparingOrder, id)
	return err
}

const updateOrderTotal = `-- name: UpdateOrderTotal :exec
UPDATE orders
SET order_total = $1,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateOrderTotalParams struct {
	OrderTotal int32 `json:"order_total"`
	ID         int32 `json:"id"`
}

func (q *Queries) UpdateOrderTotal(ctx context.Context, arg UpdateOrderTotalParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderTotal, arg.OrderTotal, arg.ID)
	return err
}
