// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orderItemModifiers.sql

package db

import (
	"context"
)

const createOrderItemModifier = `-- name: CreateOrderItemModifier :one
INSERT INTO order_item_modifiers (
    order_item_id,
    modifier_group_name_snapshot,
    modifier_item_name_snapshot,
    modifier_price,
    quantity
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, order_item_id, modifier_group_name_snapshot, modifier_item_name_snapshot, modifier_price, quantity
`

type CreateOrderItemModifierParams struct {
	OrderItemID               int32  `json:"order_item_id"`
	ModifierGroupNameSnapshot string `json:"modifier_group_name_snapshot"`
	ModifierItemNameSnapshot  string `json:"modifier_item_name_snapshot"`
	ModifierPrice             int32  `json:"modifier_price"`
	Quantity                  int32  `json:"quantity"`
}

func (q *Queries) CreateOrderItemModifier(ctx context.Context, arg CreateOrderItemModifierParams) (OrderItemModifier, error) {
	row := q.db.QueryRowContext(ctx, createOrderItemModifier,
		arg.OrderItemID,
		arg.ModifierGroupNameSnapshot,
		arg.ModifierItemNameSnapshot,
		arg.ModifierPrice,
		arg.Quantity,
	)
	var i OrderItemModifier
	err := row.Scan(
		&i.ID,
		&i.OrderItemID,
		&i.ModifierGroupNameSnapshot,
		&i.ModifierItemNameSnapshot,
		&i.ModifierPrice,
		&i.Quantity,
	)
	return i, err
}
