// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orderItems.sql

package db

import (
	"context"
	"database/sql"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id,
    menu_id,
    menu_name_snapshot,
    unit_price,
    quantity,
    modifiers_total,
    item_total
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
) RETURNING id, order_id, menu_id, menu_name_snapshot, unit_price, quantity, modifiers_total, item_total
`

type CreateOrderItemParams struct {
	OrderID          int32  `json:"order_id"`
	MenuID           int32  `json:"menu_id"`
	MenuNameSnapshot string `json:"menu_name_snapshot"`
	UnitPrice        int32  `json:"unit_price"`
	Quantity         int32  `json:"quantity"`
	ModifiersTotal   int32  `json:"modifiers_total"`
	ItemTotal        int32  `json:"item_total"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.OrderID,
		arg.MenuID,
		arg.MenuNameSnapshot,
		arg.UnitPrice,
		arg.Quantity,
		arg.ModifiersTotal,
		arg.ItemTotal,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.MenuID,
		&i.MenuNameSnapshot,
		&i.UnitPrice,
		&i.Quantity,
		&i.ModifiersTotal,
		&i.ItemTotal,
	)
	return i, err
}

const getAllOrderItems = `-- name: GetAllOrderItems :many
SELECT
    oi.id AS order_item_id,
    oi.menu_name_snapshot,
    oi.unit_price,
    oi.quantity AS item_quantity,
    oi.item_total,
    oim.modifier_group_name_snapshot,
    oim.modifier_item_name_snapshot,
    oim.modifier_price,
    oim.quantity AS modifier_quantity
FROM order_items oi
LEFT JOIN order_item_modifiers oim
    ON oi.id = oim.order_item_id
WHERE oi.order_id = $1
ORDER BY oi.id
`

type GetAllOrderItemsRow struct {
	OrderItemID               int32          `json:"order_item_id"`
	MenuNameSnapshot          string         `json:"menu_name_snapshot"`
	UnitPrice                 int32          `json:"unit_price"`
	ItemQuantity              int32          `json:"item_quantity"`
	ItemTotal                 int32          `json:"item_total"`
	ModifierGroupNameSnapshot sql.NullString `json:"modifier_group_name_snapshot"`
	ModifierItemNameSnapshot  sql.NullString `json:"modifier_item_name_snapshot"`
	ModifierPrice             sql.NullInt32  `json:"modifier_price"`
	ModifierQuantity          sql.NullInt32  `json:"modifier_quantity"`
}

func (q *Queries) GetAllOrderItems(ctx context.Context, orderID int32) ([]GetAllOrderItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllOrderItemsRow
	for rows.Next() {
		var i GetAllOrderItemsRow
		if err := rows.Scan(
			&i.OrderItemID,
			&i.MenuNameSnapshot,
			&i.UnitPrice,
			&i.ItemQuantity,
			&i.ItemTotal,
			&i.ModifierGroupNameSnapshot,
			&i.ModifierItemNameSnapshot,
			&i.ModifierPrice,
			&i.ModifierQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
