// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package db

import (
	"context"
	"database/sql"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    order_id,
    external_id,
    gateway_name,
    payment_channel,
    amount,
    status
  )
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    'pending'
  )
RETURNING id, order_id, external_id, gateway_transaction_id, gateway_name, amount, payment_channel, status, paid_at, created_at, updated_at
`

type CreatePaymentParams struct {
	OrderID        int32          `json:"order_id"`
	ExternalID     string         `json:"external_id"`
	GatewayName    string         `json:"gateway_name"`
	PaymentChannel sql.NullString `json:"payment_channel"`
	Amount         int32          `json:"amount"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.OrderID,
		arg.ExternalID,
		arg.GatewayName,
		arg.PaymentChannel,
		arg.Amount,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ExternalID,
		&i.GatewayTransactionID,
		&i.GatewayName,
		&i.Amount,
		&i.PaymentChannel,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllPayments = `-- name: GetAllPayments :many
SELECT id, order_id, external_id, gateway_transaction_id, gateway_name, amount, payment_channel, status, paid_at, created_at, updated_at
FROM payments
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type GetAllPaymentsParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) GetAllPayments(ctx context.Context, arg GetAllPaymentsParams) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, getAllPayments, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ExternalID,
			&i.GatewayTransactionID,
			&i.GatewayName,
			&i.Amount,
			&i.PaymentChannel,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentByExternalID = `-- name: GetPaymentByExternalID :many
SELECT id, order_id, external_id, gateway_transaction_id, gateway_name, amount, payment_channel, status, paid_at, created_at, updated_at
FROM payments
WHERE external_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type GetPaymentByExternalIDParams struct {
	ExternalID string `json:"external_id"`
	Offset     int32  `json:"offset"`
	Limit      int32  `json:"limit"`
}

func (q *Queries) GetPaymentByExternalID(ctx context.Context, arg GetPaymentByExternalIDParams) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, getPaymentByExternalID, arg.ExternalID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ExternalID,
			&i.GatewayTransactionID,
			&i.GatewayName,
			&i.Amount,
			&i.PaymentChannel,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentsByOrderID = `-- name: GetPaymentsByOrderID :many
SELECT id, order_id, external_id, gateway_transaction_id, gateway_name, amount, payment_channel, status, paid_at, created_at, updated_at
FROM payments
WHERE order_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type GetPaymentsByOrderIDParams struct {
	OrderID int32 `json:"order_id"`
	Offset  int32 `json:"offset"`
	Limit   int32 `json:"limit"`
}

func (q *Queries) GetPaymentsByOrderID(ctx context.Context, arg GetPaymentsByOrderIDParams) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, getPaymentsByOrderID, arg.OrderID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ExternalID,
			&i.GatewayTransactionID,
			&i.GatewayName,
			&i.Amount,
			&i.PaymentChannel,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentExpired = `-- name: MarkPaymentExpired :exec
UPDATE payments
SET status = 'expired',
  updated_at = CURRENT_TIMESTAMP
WHERE external_id = $1
  AND status = 'pending'
`

func (q *Queries) MarkPaymentExpired(ctx context.Context, externalID string) error {
	_, err := q.db.ExecContext(ctx, markPaymentExpired, externalID)
	return err
}

const markPaymentFailed = `-- name: MarkPaymentFailed :exec
UPDATE payments
SET status = 'failed',
  updated_at = CURRENT_TIMESTAMP
WHERE external_id = $1
  AND status = 'pending'
`

func (q *Queries) MarkPaymentFailed(ctx context.Context, externalID string) error {
	_, err := q.db.ExecContext(ctx, markPaymentFailed, externalID)
	return err
}

const markPaymentPaid = `-- name: MarkPaymentPaid :exec
UPDATE payments
SET status = 'paid',
  payment_channel = $1,
  gateway_transaction_id = $2,
  paid_at = CURRENT_TIMESTAMP,
  updated_at = CURRENT_TIMESTAMP
WHERE external_id = $3
  AND status = 'pending'
`

type MarkPaymentPaidParams struct {
	PaymentChannel       sql.NullString `json:"payment_channel"`
	GatewayTransactionID sql.NullString `json:"gateway_transaction_id"`
	ExternalID           string         `json:"external_id"`
}

func (q *Queries) MarkPaymentPaid(ctx context.Context, arg MarkPaymentPaidParams) error {
	_, err := q.db.ExecContext(ctx, markPaymentPaid, arg.PaymentChannel, arg.GatewayTransactionID, arg.ExternalID)
	return err
}

const markPaymentSettled = `-- name: MarkPaymentSettled :exec
UPDATE payments
SET status = 'settled',
  updated_at = CURRENT_TIMESTAMP
WHERE external_id = $1
  AND status = 'paid'
`

func (q *Queries) MarkPaymentSettled(ctx context.Context, externalID string) error {
	_, err := q.db.ExecContext(ctx, markPaymentSettled, externalID)
	return err
}
